name: CI Guardrails

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'apps/backend/**'
      - 'apps/web-verify/**'
      - 'packages/shared/**'
      - 'pnpm-lock.yaml'

jobs:
  backend-checks:
    name: Backend Guardrails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build shared package first
        run: pnpm --filter @verifd/shared build
        
      - name: Check TypeScript
        run: pnpm --filter @verifd/backend build
        
      - name: Run backend tests
        run: |
          pnpm --filter @verifd/backend test --run || true
          
      - name: Test backend starts
        run: |
          # Navigate to backend directory and create test database directory
          cd apps/backend
          mkdir -p var/db
          
          # Start backend in background on port 3002 from backend directory
          PORT=3002 NODE_ENV=test DB_PATH=var/db/test.db pnpm dev &
          BACKEND_PID=$!
          
          # Wait for backend to be ready with proper health check
          echo "Waiting for backend to be ready..."
          for i in {1..30}; do
            if curl -f -s http://localhost:3002/health/healthz >/dev/null 2>&1; then
              echo "✅ Backend is ready at http://localhost:3002/health/healthz"
              break
            fi
            echo "⏳ Backend not ready yet (attempt $i/30)..."
            sleep 2
            if [ $i -eq 30 ]; then
              echo "❌ Backend failed to start within 60 seconds"
              curl -v http://localhost:3002/health/healthz || true
              exit 1
            fi
          done
          
          # Test main health endpoint too
          curl -f http://localhost:3002/health/ || exit 1
          
          # Backend is running successfully
          echo "✅ Backend health check passed"
          
          # Kill backend
          kill $BACKEND_PID
        env:
          PORT: 3002
          NODE_ENV: test
          DB_PATH: var/db/test.db
          JWT_SECRET: test-secret-for-ci
          HMAC_SECRET: test-hmac-secret-for-ci
          
  web-verify-checks:
    name: Web Verify Guardrails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build shared package first
        run: pnpm --filter @verifd/shared build
        
      - name: Check TypeScript
        run: pnpm --filter @verifd/web-verify build
        
      - name: Check for console.log statements
        run: |
          if grep -r "console\.log" apps/web-verify/src --exclude-dir=node_modules; then
            echo "::warning::Found console.log statements in production code"
          fi
          
      - name: Verify environment variables
        run: |
          # Check that .env.example exists
          test -f apps/web-verify/.env.example || echo "::warning::Missing .env.example"
          
  security-checks:
    name: Security Guardrails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for exposed secrets
        run: |
          # Check for potential secrets (excluding .github directory to avoid self-matches)
          if grep -r "sk_live\|pk_live\|AKIA" . \
            --exclude-dir=node_modules \
            --exclude-dir=.git \
            --exclude-dir=.github \
            --exclude-dir=playwright-report \
            --exclude-dir=test-results; then
            echo "::error::Potential secrets found in code!"
            exit 1
          fi
          
          # Check aws_secret pattern separately, excluding this workflow file
          if grep -r "aws_secret" . \
            --exclude-dir=node_modules \
            --exclude-dir=.git \
            --exclude-dir=.github \
            --exclude-dir=playwright-report \
            --exclude-dir=test-results \
            --exclude="*.yml"; then
            echo "::error::Potential AWS secrets found in code!"
            exit 1
          fi
          
      - name: Check for hardcoded URLs
        run: |
          # Warn about hardcoded production URLs
          if grep -r "https://verify\.getpryvacy\.com" apps/backend/src apps/web-verify/src --exclude="*.test.*" --exclude="*.example"; then
            echo "::warning::Found hardcoded production URLs - should use environment variables"
          fi
          
  monorepo-integrity:
    name: Monorepo Integrity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          
      - name: Check workspace dependencies
        run: |
          # Verify all workspace packages can be resolved
          pnpm ls --depth 0
          
      - name: Check for duplicate dependencies
        run: |
          # Find duplicate dependencies across workspaces
          pnpm dedupe --check